services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password 
    # Work in github actions
    network_mode: host
    # Work in local dev
    # ports:
    #   - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

