name: build and deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build Docker image
        run: make build-image
      
      - name: Save Docker image
        run: make build-image-save
      
      - name: Cache Docker image
        uses: actions/cache/save@v3
        with:
          path: /tmp/docker-image.tar
          key: docker-image-${{ github.sha }}
      
      - name: Push Image
        run: make build-image-push
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION}}
    
  test:
    needs: 
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Docker image from cache
        uses: actions/cache/restore@v3
        with:
          path: /tmp/docker-image.tar
          key: docker-image-${{ github.sha }}
          fail-on-cache-miss: true
      
      - name: Load Docker image
        run: make build-image-load
      
      - name: Start Docker containers
        run: make up

      - name: Test Migrations
        run: make build-image-migrate
        env:
          GOOSE_DRIVER: postgres
          GOOSE_DBSTRING: postgresql://postgres:password@localhost:5432/postgres?sslmode=disable

      - name: Stop Docker containers
        if: always()
        run: make down